apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  restartPolicy: OnFailure              
  containers:
  - name: hello
    image: "ubuntu:14.04"
    command: ["/bin/echo","Hello","world"]