apiVersion: v1
kind: ReplicationController
metadata: 
  name: mysql
spec:
  replicas: 1
  selector:
    app: mysql
  template:
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 13306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "114114"
    metadata:
      labels:
        app: mysql